name: tiktok_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  video_player: ^2.9.5
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  flutter_bloc: ^7.2.0
  http: ^1.3.0
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: 
  image_path: "assets/images/logo.png"  # PNG format only


